# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aa_runif <- function(n, seed) {
    .Call('_aarand_aa_runif', PACKAGE = 'aarand', n, seed)
}

aa_rnorm <- function(n, seed) {
    .Call('_aarand_aa_rnorm', PACKAGE = 'aarand', n, seed)
}

aa_rexp <- function(n, seed) {
    .Call('_aarand_aa_rexp', PACKAGE = 'aarand', n, seed)
}

aa_shuffle <- function(input, seed) {
    .Call('_aarand_aa_shuffle', PACKAGE = 'aarand', input, seed)
}

aa_sample <- function(input, s, seed) {
    .Call('_aarand_aa_sample', PACKAGE = 'aarand', input, s, seed)
}

aa_sample_n <- function(n, s, seed) {
    .Call('_aarand_aa_sample_n', PACKAGE = 'aarand', n, s, seed)
}

